"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React,{useState} from "react";
import Sidebar from "./sidebar/page"

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  const [isOpen, setIsOpen] = useState(false);

  const handleToggle = (isOpen: boolean) => {
      setIsOpen(isOpen);
  };

  return (
    <html lang="en">
      <body className={inter.className}>
      <Sidebar onToggle={handleToggle} />
            <div className={`flex-1 p-3 md:p-10 transition-all duration-300 ${isOpen ? 'ml-64' : 'ml-16'}`}>
                <main>
                    {children}
                    
                </main>
            </div>
      </body>
    </html>
  );
}
